# Rename this file to: config.yml
# Example paths below. Please change them to suit your needs.
# Paths in /video-volume are where the video files will be shuffled around,
# and should be the same file system to avoid wait times for moving files.

running_path: RUNNING
checked_path: checked
too_big_after_path: toobigafter
working_path: /video-volume/Library/shrink-video
error_path: errors
trash_path: /video-volume/shrink-video-trash
transcoded_path: transcoded
dotfile_skip: .donotshrink
speed: medium
extensions:
  - .mkv
  - .mp4
  - .m4v
  - .avi
  - .mpg
  - .ts
  - .divx
  - .mov
  - .wmv
  - .flv
mandatory_encode:
  - .ts
  - .divx
  - .mov
  - .wmv
  - .flv
# Quality threshold, dividing bitrate by pixel area
threshold: 2.4
threshold_sm: 3.6
encode_quality: 25
max_width: 1280
delay_days: 7
